"""rich text post

Revision ID: 143f9a1e109
Revises: 464d6fe8b2a
Create Date: 2015-09-28 19:54:46.574052

"""

# revision identifiers, used by Alembic.
revision = '143f9a1e109'
down_revision = '464d6fe8b2a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
