"""empty message

Revision ID: 19f404c65f
Revises: 29c2ca0e29f
Create Date: 2015-09-26 21:55:29.233368

"""

# revision identifiers, used by Alembic.
revision = '19f404c65f'
down_revision = '29c2ca0e29f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    ### end Alembic commands ###
