"""empty message

Revision ID: 221d39f2ed3
Revises: 4f149f9f04a
Create Date: 2015-09-28 16:49:01.665155

"""

# revision identifiers, used by Alembic.
revision = '221d39f2ed3'
down_revision = '4f149f9f04a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
